package com.sih.faceattendance.ui.screens.enrollment

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Matrix
import android.util.Log
import androidx.camera.core.CameraSelector
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.Preview
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.camera.view.PreviewView
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalLifecycleOwner
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import androidx.core.content.ContextCompat
import com.sih.faceattendance.AttendanceApplication
import com.sih.faceattendance.core.*
import com.sih.faceattendance.data.local.entities.StudentEntity
import com.sih.faceattendance.data.remote.NetworkClient
import com.sih.faceattendance.ml.DetectedFaceResult
import com.sih.faceattendance.ui.components.StudentAvatar
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.util.concurrent.Executors
import kotlin.math.abs
import kotlin.math.sqrt

data class CourseBatchOption(val courseName: String, val batchCode: String)

val DEFAULT_COURSES = listOf(
    CourseBatchOption("Digital Literacy", "DL-01"),
    CourseBatchOption("Cooperative Management", "CM-02"),
    CourseBatchOption("Entrepreneurship Development", "EN-03"),
    CourseBatchOption("Agri-Cooperative Banking", "AB-04"),
    CourseBatchOption("Rural Credit & Finance", "RC-05")
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EnrollmentScreen(
    onEnrollmentComplete: () -> Unit = {}
) {
    val context = LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current
    val app = context.applicationContext as AttendanceApplication
    val scope = rememberCoroutineScope()

    // 0 = New Student Face Enrollment, 1 = Enroll Existing Student in Course
    var enrollmentMode by remember { mutableIntStateOf(0) }

    var name by remember { mutableStateOf("") }
    // Auto-generated preview ID based on current timestamp
    val autoGeneratedStudentId = remember { "NCCT${(System.currentTimeMillis() % 9000 + 1000)}" }
    val autoGeneratedRoll = remember { "${(100..199).random()}" }

    // Course & Batch selection state with dropdown
    var selectedCourseOption by remember { mutableStateOf(DEFAULT_COURSES[0]) }
    var isCourseDropdownExpanded by remember { mutableStateOf(false) }

    // Existing Student Course Enrollment State
    val allStudents by app.studentRepository.allStudentsFlow.collectAsState(initial = emptyList<StudentEntity>())
    var selectedExistingStudent by remember { mutableStateOf<StudentEntity?>(null) }
    var isExistingStudentDropdownExpanded by remember { mutableStateOf(false) }
    var existingEnrollSuccessMessage by remember { mutableStateOf<String?>(null) }

    var latestFrameBitmap by remember { mutableStateOf<Bitmap?>(null) }
    var capturedFrontFaceBitmap by remember { mutableStateOf<Bitmap?>(null) }
    var capturedLeftFaceBitmap by remember { mutableStateOf<Bitmap?>(null) }
    var capturedRightFaceBitmap by remember { mutableStateOf<Bitmap?>(null) }
    var enrolledStudent by remember { mutableStateOf<StudentEntity?>(null) }
    var isProcessingAngle by remember { mutableStateOf(false) }
    var duplicateErrorText by remember { mutableStateOf<String?>(null) }
    var conflictingStudent by remember { mutableStateOf<StudentEntity?>(null) }
    var pendingAggregatedVector by remember { mutableStateOf<FloatArray?>(null) }

    // Biometric Modal Popup State
    var showBiometricModal by remember { mutableStateOf(false) }
    var registrationStep by remember { mutableStateOf(1) } // 1: Frontal, 2: Left, 3: Right, 4: Blink, 5: Done
    var blinkDetected by remember { mutableStateOf(false) }
    val capturedVectors = remember { mutableStateListOf<FloatArray>() }
    var guidanceMessage by remember { mutableStateOf("Look straight at the camera") }

    // Live Head Pose Tracking State (Auto-Enrollment Engine)
    var faceDetectedInCircle by remember { mutableStateOf(false) }
    var currentYaw by remember { mutableStateOf(0f) }
    var currentPitch by remember { mutableStateOf(0f) }
    var holdCount by remember { mutableStateOf(0) }
    var holdProgress by remember { mutableStateOf(0f) }
    var firstTurnDirection by remember { mutableStateOf(0) } // -1 for left, +1 for right
    var isSuccessAnimation by remember { mutableStateOf(false) }

    // Smooth animated progress value for outer circular ring (0 -> 25% -> 50% -> 75% -> 100%)
    val animatedProgress by animateFloatAsState(
        targetValue = when (registrationStep) {
            1 -> 0.05f
            2 -> 0.28f
            3 -> 0.55f
            4 -> 0.82f
            else -> 1.0f
        },
        animationSpec = tween(durationMillis = 450),
        label = "biometric_progress"
    )

    // Function to register student with a given embedding vector and frontal photo
    fun registerStudentWithVector(vector: FloatArray, frontCrop: Bitmap) {
        scope.launch(Dispatchers.Default) {
            try {
                // Delete prior conflicting profile if replacing
                conflictingStudent?.let { old ->
                    app.studentRepository.deleteStudent(old.studentId)
                }

                val finalStudentId = autoGeneratedStudentId
                val finalRoll = autoGeneratedRoll
                val finalName = if (name.isBlank()) "Student $finalStudentId" else name.trim()
                val studentsDir = File(context.filesDir, "enrolled_students")
                if (!studentsDir.exists()) studentsDir.mkdirs()
                val photoFile = File(studentsDir, "$finalStudentId.jpg")
                withContext(Dispatchers.IO) {
                    val fos = FileOutputStream(photoFile)
                    frontCrop.compress(Bitmap.CompressFormat.JPEG, 92, fos)
                    fos.flush()
                    fos.close()
                }

                val student = app.studentRepository.enrollStudent(
                    studentId = finalStudentId,
                    name = finalName,
                    rollNumber = finalRoll,
                    course = selectedCourseOption.courseName,
                    enrolledSessionIds = listOf(selectedCourseOption.batchCode),
                    faceEmbedding = vector,
                    photoUri = photoFile.absolutePath
                )

                // Seamlessly push newly enrolled biometric profile to central server
                scope.launch(Dispatchers.IO) {
                    try {
                        app.studentRepository.syncWithServer(NetworkClient.apiService, context)
                    } catch (_: Exception) {}
                }

                withContext(Dispatchers.Main) {
                    enrolledStudent = student
                    conflictingStudent = null
                    duplicateErrorText = null
                    pendingAggregatedVector = null
                    isSuccessAnimation = true
                    guidanceMessage = "Biometric Profile Successfully Registered! 🎉"

                    delay(2000)
                    showBiometricModal = false
                    isSuccessAnimation = false
                    isProcessingAngle = false
                }
            } catch (e: Exception) {
                Log.e("RegisterStudent", "Error saving student profile", e)
                withContext(Dispatchers.Main) {
                    isProcessingAngle = false
                }
            }
        }
    }

    // Function to finalize registration after all 3 angles + blink challenge
    fun finalizeRegistration(frontCrop: Bitmap) {
        if (isProcessingAngle) return
        isProcessingAngle = true

        scope.launch(Dispatchers.Default) {
            try {
                // 1. Fuse the multi-angle embeddings into an averaged unit-norm vector
                val embDim = app.faceEmbeddingEngine.getEmbeddingDimension()
                val aggregated = FloatArray(embDim)
                for (vec in capturedVectors) {
                    for (i in 0 until minOf(embDim, vec.size)) {
                        aggregated[i] += vec[i]
                    }
                }
                var norm = 0.0
                for (i in 0 until embDim) {
                    aggregated[i] /= maxOf(1, capturedVectors.size).toFloat()
                    norm += (aggregated[i] * aggregated[i]).toDouble()
                }
                norm = sqrt(norm)
                if (norm > 0) {
                    for (i in 0 until embDim) {
                        aggregated[i] = (aggregated[i] / norm).toFloat()
                    }
                }
                pendingAggregatedVector = aggregated

                // 2. DUPLICATE FACE VALIDATION: Prevent one person from enrolling under multiple IDs/names!
                // Calibrated duplicate threshold of 0.55f prevents duplicate registrations across web & mobile
                val duplicate = app.studentRepository.findDuplicateFace(aggregated, threshold = 0.55f)
                if (duplicate != null) {
                    withContext(Dispatchers.Main) {
                        conflictingStudent = duplicate.first
                        duplicateErrorText = "Biometric Conflict: This face matches registered student '${duplicate.first.name}' (ID: ${duplicate.first.studentId}, ${(duplicate.second * 100).toInt()}% match)."
                        isProcessingAngle = false
                    }
                    return@launch
                }

                // 3. Register unique student profile
                registerStudentWithVector(aggregated, frontCrop)
            } catch (e: Exception) {
                Log.e("FinalizeEnrollment", "Error finalizing enrollment", e)
                withContext(Dispatchers.Main) {
                    isProcessingAngle = false
                }
            }
        }
    }

    // Function to capture angle and extract embedding
    fun captureCurrentAngle(step: Int, frame: Bitmap, face: DetectedFaceResult) {
        if (isProcessingAngle) return
        isProcessingAngle = true

        scope.launch(Dispatchers.Default) {
            try {
                val box = face.boundingBox
                val alignedFace = app.faceEmbeddingEngine.alignFace(
                    sourceBitmap = frame,
                    eye1 = face.leftEyePosition,
                    eye2 = face.rightEyePosition,
                    boundingBox = box
                )

                // Extract MobileFaceNet embedding (192-dim)
                val vector = app.faceEmbeddingEngine.extractEmbedding(alignedFace)

                withContext(Dispatchers.Main) {
                    capturedVectors.add(vector)

                    when (step) {
                        1 -> {
                            capturedFrontFaceBitmap = alignedFace
                            registrationStep = 2
                            guidanceMessage = "Frontal captured ✓ Now turn your head SLOWLY LEFT 👈"
                            isProcessingAngle = false
                        }
                        2 -> {
                            capturedLeftFaceBitmap = alignedFace
                            registrationStep = 3
                            guidanceMessage = "Left angle captured ✓ Now turn your head SLOWLY RIGHT 👉"
                            isProcessingAngle = false
                        }
                        3 -> {
                            capturedRightFaceBitmap = alignedFace
                            registrationStep = 4
                            blinkDetected = false
                            guidanceMessage = "Right angle captured ✓ Step 4/4: Blink both eyes naturally 👁️"
                            isProcessingAngle = false
                        }
                    }
                }
            } catch (e: Exception) {
                Log.e("CaptureAngle", "Error capturing angle", e)
                withContext(Dispatchers.Main) {
                    isProcessingAngle = false
                }
            }
        }
    }

    // Function to start a fresh auto-enrollment session
    fun startBiometricEnrollment() {
        capturedVectors.clear()
        capturedFrontFaceBitmap = null
        capturedLeftFaceBitmap = null
        capturedRightFaceBitmap = null
        registrationStep = 1
        blinkDetected = false
        holdCount = 0
        holdProgress = 0f
        firstTurnDirection = 0
        isProcessingAngle = false
        isSuccessAnimation = false
        duplicateErrorText = null
        conflictingStudent = null
        pendingAggregatedVector = null
        guidanceMessage = "Look straight at the camera"
        showBiometricModal = true
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text(
                            text = "1. Student Biometric Enrollment",
                            fontSize = 16.sp,
                            fontWeight = FontWeight.Bold,
                            color = TextPrimary
                        )
                        Text(
                            text = "Auto-Detect Multi-Angle Face Registration (FaceID Style)",
                            fontSize = 12.sp,
                            color = PrimaryBlue,
                            fontWeight = FontWeight.Medium
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = LightSurface)
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .background(LightBackground)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Production Onboarding Explanatory Banner
            Surface(
                color = PrimaryBlueContainer,
                shape = RoundedCornerShape(12.dp),
                border = androidx.compose.foundation.BorderStroke(1.dp, PrimaryBlue.copy(alpha = 0.25f))
            ) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(14.dp),
                    verticalAlignment = Alignment.Top,
                    horizontalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Icon(Icons.Default.Info, contentDescription = null, tint = PrimaryBlue, modifier = Modifier.size(24.dp))
                    Column(modifier = Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                        Text(
                            text = "PILOT BIOMETRIC ENROLLMENT MODULE",
                            color = PrimaryBlue,
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold
                        )
                        Text(
                            text = "Note: In the live production system, biometric enrollment is completed once during student onboarding for the course. In this trial prototype, enrollment is accessible upfront to demonstrate 3D multi-angle capture and instant local inference.",
                            color = TextSecondary,
                            fontSize = 11.sp,
                            lineHeight = 16.sp
                        )
                    }
                }
            }

            // Mode Selector: New Student vs Enroll Existing Student in Course
            Surface(
                color = LightSurface,
                shape = RoundedCornerShape(12.dp),
                border = androidx.compose.foundation.BorderStroke(1.dp, LightCardBorder)
            ) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(4.dp),
                    horizontalArrangement = Arrangement.spacedBy(4.dp)
                ) {
                    Surface(
                        modifier = Modifier
                            .weight(1f)
                            .clickable { enrollmentMode = 0 },
                        color = if (enrollmentMode == 0) PrimaryBlue else Color.Transparent,
                        shape = RoundedCornerShape(8.dp)
                    ) {
                        Row(
                            modifier = Modifier.padding(vertical = 10.dp, horizontal = 8.dp),
                            horizontalArrangement = Arrangement.Center,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                Icons.Default.PersonAdd,
                                contentDescription = null,
                                tint = if (enrollmentMode == 0) Color.White else TextSecondary,
                                modifier = Modifier.size(16.dp)
                            )
                            Spacer(Modifier.width(6.dp))
                            Text(
                                text = "New Student",
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Bold,
                                color = if (enrollmentMode == 0) Color.White else TextSecondary
                            )
                        }
                    }

                    Surface(
                        modifier = Modifier
                            .weight(1f)
                            .clickable { enrollmentMode = 1 },
                        color = if (enrollmentMode == 1) PrimaryBlue else Color.Transparent,
                        shape = RoundedCornerShape(8.dp)
                    ) {
                        Row(
                            modifier = Modifier.padding(vertical = 10.dp, horizontal = 8.dp),
                            horizontalArrangement = Arrangement.Center,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                Icons.Default.LibraryAdd,
                                contentDescription = null,
                                tint = if (enrollmentMode == 1) Color.White else TextSecondary,
                                modifier = Modifier.size(16.dp)
                            )
                            Spacer(Modifier.width(6.dp))
                            Text(
                                text = "Existing Student",
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Bold,
                                color = if (enrollmentMode == 1) Color.White else TextSecondary
                            )
                        }
                    }
                }
            }

            if (enrollmentMode == 0) {
                // ==================== MODE 0: NEW STUDENT BIOMETRIC ENROLLMENT ====================
                Card(
                    colors = CardDefaults.cardColors(containerColor = LightSurface),
                    shape = RoundedCornerShape(14.dp),
                    border = androidx.compose.foundation.BorderStroke(1.dp, LightCardBorder),
                    elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(16.dp),
                        verticalArrangement = Arrangement.spacedBy(14.dp)
                    ) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                text = "NEW STUDENT ENROLLMENT",
                                fontSize = 11.sp,
                                fontWeight = FontWeight.Bold,
                                color = PrimaryBlue,
                                letterSpacing = 0.5.sp
                            )
                            Surface(
                                color = SkyContainer,
                                shape = RoundedCornerShape(6.dp)
                            ) {
                                Text(
                                    text = "Auto-ID: $autoGeneratedStudentId",
                                    fontSize = 11.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = PrimaryBlue,
                                    modifier = Modifier.padding(horizontal = 8.dp, vertical = 3.dp)
                                )
                            }
                        }

                        // Full Name Input Only
                        OutlinedTextField(
                            value = name,
                            onValueChange = { name = it },
                            label = { Text("Full Name *") },
                            placeholder = { Text("e.g. Nishant Maurya") },
                            modifier = Modifier.fillMaxWidth(),
                            singleLine = true,
                            leadingIcon = { Icon(Icons.Default.Person, contentDescription = null, tint = TextSecondary) },
                            shape = RoundedCornerShape(10.dp),
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedContainerColor = LightSurface,
                                unfocusedContainerColor = LightSurface,
                                focusedBorderColor = PrimaryBlue,
                                unfocusedBorderColor = LightCardBorder
                            )
                        )

                        // Trial Fields Disclaimer Note
                        Surface(
                            color = LightSubtle,
                            shape = RoundedCornerShape(10.dp),
                            border = androidx.compose.foundation.BorderStroke(1.dp, LightCardBorder)
                        ) {
                            Column(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(12.dp),
                                verticalArrangement = Arrangement.spacedBy(4.dp)
                            ) {
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    Icon(Icons.Default.FactCheck, contentDescription = null, tint = PrimaryBlue, modifier = Modifier.size(16.dp))
                                    Text(
                                        text = "Production Onboarding Data Fields:",
                                        fontSize = 11.sp,
                                        fontWeight = FontWeight.Bold,
                                        color = TextPrimary
                                    )
                                }
                                Text(
                                    text = "• Student ID & Roll Number: Auto-assigned ($autoGeneratedStudentId / Roll #$autoGeneratedRoll)\n• Production Fields (Aadhaar / Voter ID, Biometric Consent, Father's Name, DOB, Center Code) will be captured during institutional onboarding. Only Full Name is required for this trial.",
                                    fontSize = 11.sp,
                                    color = TextSecondary,
                                    lineHeight = 16.sp
                                )
                            }
                        }

                        // COURSE SELECTION DROPDOWN
                        ExposedDropdownMenuBox(
                            expanded = isCourseDropdownExpanded,
                            onExpandedChange = { isCourseDropdownExpanded = it },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            OutlinedTextField(
                                value = "${selectedCourseOption.courseName} (${selectedCourseOption.batchCode})",
                                onValueChange = {},
                                readOnly = true,
                                label = { Text("Enrolled Course & Batch") },
                                trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = isCourseDropdownExpanded) },
                                leadingIcon = { Icon(Icons.Default.School, contentDescription = null, tint = PrimaryBlue) },
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .menuAnchor(MenuAnchorType.PrimaryNotEditable, true),
                                shape = RoundedCornerShape(10.dp),
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedContainerColor = LightSurface,
                                    unfocusedContainerColor = LightSurface,
                                    focusedBorderColor = PrimaryBlue,
                                    unfocusedBorderColor = LightCardBorder
                                )
                            )

                            ExposedDropdownMenu(
                                expanded = isCourseDropdownExpanded,
                                onDismissRequest = { isCourseDropdownExpanded = false },
                                modifier = Modifier.background(LightSurface)
                            ) {
                                DEFAULT_COURSES.forEach { option ->
                                    DropdownMenuItem(
                                        text = {
                                            Column {
                                                Text(option.courseName, fontWeight = FontWeight.SemiBold, fontSize = 14.sp, color = TextPrimary)
                                                Text("Batch Code: ${option.batchCode}", fontSize = 11.sp, color = PrimaryBlue)
                                            }
                                        },
                                        onClick = {
                                            selectedCourseOption = option
                                            isCourseDropdownExpanded = false
                                        }
                                    )
                                }
                            }
                        }

                        // Start Registration Button
                        Button(
                            onClick = { startBiometricEnrollment() },
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(52.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue),
                            shape = RoundedCornerShape(12.dp)
                        ) {
                            Icon(Icons.Default.Face, contentDescription = null)
                            Spacer(Modifier.width(8.dp))
                            Text(
                                text = "START AUTO FACE REGISTRATION",
                                fontWeight = FontWeight.Bold,
                                fontSize = 14.sp
                            )
                        }
                    }
                }
            } else {
                // ==================== MODE 1: ENROLL EXISTING STUDENT IN ANOTHER COURSE ====================
                Card(
                    colors = CardDefaults.cardColors(containerColor = LightSurface),
                    shape = RoundedCornerShape(14.dp),
                    border = androidx.compose.foundation.BorderStroke(1.dp, LightCardBorder),
                    elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(16.dp),
                        verticalArrangement = Arrangement.spacedBy(14.dp)
                    ) {
                        Text(
                            text = "ENROLL EXISTING STUDENT IN ADDITIONAL COURSE",
                            fontSize = 11.sp,
                            fontWeight = FontWeight.Bold,
                            color = PrimaryBlue,
                            letterSpacing = 0.5.sp
                        )

                        Text(
                            text = "Select any previously registered student from the local database to enroll them into another course/batch without re-scanning their face.",
                            fontSize = 11.sp,
                            color = TextSecondary,
                            lineHeight = 16.sp
                        )

                        // SELECT EXISTING STUDENT DROPDOWN
                        ExposedDropdownMenuBox(
                            expanded = isExistingStudentDropdownExpanded,
                            onExpandedChange = { isExistingStudentDropdownExpanded = it },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            OutlinedTextField(
                                value = selectedExistingStudent?.let { "${it.name} (${it.studentId})" } ?: "Select Registered Student (${allStudents.size} available)",
                                onValueChange = {},
                                readOnly = true,
                                label = { Text("Registered Student") },
                                trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = isExistingStudentDropdownExpanded) },
                                leadingIcon = { Icon(Icons.Default.AccountCircle, contentDescription = null, tint = PrimaryBlue) },
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .menuAnchor(MenuAnchorType.PrimaryNotEditable, true),
                                shape = RoundedCornerShape(10.dp),
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedContainerColor = LightSurface,
                                    unfocusedContainerColor = LightSurface,
                                    focusedBorderColor = PrimaryBlue,
                                    unfocusedBorderColor = LightCardBorder
                                )
                            )

                            ExposedDropdownMenu(
                                expanded = isExistingStudentDropdownExpanded,
                                onDismissRequest = { isExistingStudentDropdownExpanded = false },
                                modifier = Modifier
                                    .background(LightSurface)
                                    .heightIn(max = 280.dp)
                            ) {
                                if (allStudents.isEmpty()) {
                                    DropdownMenuItem(
                                        text = { Text("No students registered yet", color = TextSecondary) },
                                        onClick = { isExistingStudentDropdownExpanded = false }
                                    )
                                } else {
                                    for (std in allStudents) {
                                        DropdownMenuItem(
                                            text = {
                                                Row(
                                                    verticalAlignment = Alignment.CenterVertically,
                                                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                                                ) {
                                                    StudentAvatar(photoUri = std.photoUri, size = 36.dp)
                                                    Column {
                                                        Text(std.name, fontWeight = FontWeight.Bold, fontSize = 13.sp, color = TextPrimary)
                                                        Text("${std.studentId} • Courses: ${std.enrolledSessionIds.joinToString(", ")}", fontSize = 11.sp, color = PrimaryBlue)
                                                    }
                                                }
                                            },
                                            onClick = {
                                                selectedExistingStudent = std
                                                isExistingStudentDropdownExpanded = false
                                                existingEnrollSuccessMessage = null
                                            }
                                        )
                                    }
                                }
                            }
                        }

                        // SELECTED STUDENT PROFILE CARD
                        selectedExistingStudent?.let { std ->
                            Surface(
                                color = LightSubtle,
                                shape = RoundedCornerShape(10.dp),
                                border = androidx.compose.foundation.BorderStroke(1.dp, LightCardBorder)
                            ) {
                                Row(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .padding(12.dp),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.spacedBy(12.dp)
                                ) {
                                    StudentAvatar(photoUri = std.photoUri, size = 56.dp)
                                    Column(verticalArrangement = Arrangement.spacedBy(3.dp)) {
                                        Text(std.name, fontWeight = FontWeight.Bold, fontSize = 14.sp, color = TextPrimary)
                                        Text("ID: ${std.studentId}  •  Roll: ${std.rollNumber}", fontSize = 12.sp, color = PrimaryBlue, fontWeight = FontWeight.Medium)
                                        Text("Active Batches: ${std.enrolledSessionIds.joinToString(", ")}", fontSize = 11.sp, color = TextSecondary)
                                    }
                                }
                            }
                        }

                        // TARGET NEW COURSE DROPDOWN
                        ExposedDropdownMenuBox(
                            expanded = isCourseDropdownExpanded,
                            onExpandedChange = { isCourseDropdownExpanded = it },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            OutlinedTextField(
                                value = "${selectedCourseOption.courseName} (${selectedCourseOption.batchCode})",
                                onValueChange = {},
                                readOnly = true,
                                label = { Text("Select Course to Enroll In") },
                                trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = isCourseDropdownExpanded) },
                                leadingIcon = { Icon(Icons.Default.School, contentDescription = null, tint = PrimaryBlue) },
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .menuAnchor(MenuAnchorType.PrimaryNotEditable, true),
                                shape = RoundedCornerShape(10.dp),
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedContainerColor = LightSurface,
                                    unfocusedContainerColor = LightSurface,
                                    focusedBorderColor = PrimaryBlue,
                                    unfocusedBorderColor = LightCardBorder
                                )
                            )

                            ExposedDropdownMenu(
                                expanded = isCourseDropdownExpanded,
                                onDismissRequest = { isCourseDropdownExpanded = false },
                                modifier = Modifier.background(LightSurface)
                            ) {
                                DEFAULT_COURSES.forEach { option ->
                                    DropdownMenuItem(
                                        text = {
                                            Column {
                                                Text(option.courseName, fontWeight = FontWeight.SemiBold, fontSize = 14.sp, color = TextPrimary)
                                                Text("Batch Code: ${option.batchCode}", fontSize = 11.sp, color = PrimaryBlue)
                                            }
                                        },
                                        onClick = {
                                            selectedCourseOption = option
                                            isCourseDropdownExpanded = false
                                        }
                                    )
                                }
                            }
                        }

                        // ENROLL IN COURSE BUTTON
                        Button(
                            onClick = {
                                val std = selectedExistingStudent ?: return@Button
                                scope.launch(Dispatchers.Default) {
                                    val currentSessions = std.enrolledSessionIds.toMutableList()
                                    val newBatch = selectedCourseOption.batchCode
                                    if (!currentSessions.contains(newBatch)) {
                                        currentSessions.add(newBatch)
                                        val updatedCourse = "${std.course}, ${selectedCourseOption.courseName}"
                                        app.studentRepository.updateStudentSessions(
                                            studentId = std.studentId,
                                            newSessionIds = currentSessions,
                                            newCourse = updatedCourse
                                        )
                                        withContext(Dispatchers.Main) {
                                            existingEnrollSuccessMessage = "Successfully enrolled ${std.name} into ${selectedCourseOption.courseName} (${selectedCourseOption.batchCode})!"
                                            // Refresh local selection view
                                            selectedExistingStudent = std.copy(
                                                enrolledSessionIds = currentSessions,
                                                course = updatedCourse
                                            )
                                        }
                                    } else {
                                        withContext(Dispatchers.Main) {
                                            existingEnrollSuccessMessage = "${std.name} is ALREADY enrolled in ${selectedCourseOption.batchCode}."
                                        }
                                    }
                                }
                            },
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(50.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue),
                            shape = RoundedCornerShape(12.dp),
                            enabled = selectedExistingStudent != null
                        ) {
                            Icon(Icons.Default.Check, contentDescription = null)
                            Spacer(Modifier.width(8.dp))
                            Text(
                                text = "ENROLL IN ${selectedCourseOption.batchCode}",
                                fontWeight = FontWeight.Bold,
                                fontSize = 13.sp
                            )
                        }

                        // Success notification banner
                        existingEnrollSuccessMessage?.let { msg ->
                            Surface(
                                color = EmeraldContainer,
                                shape = RoundedCornerShape(10.dp),
                                border = androidx.compose.foundation.BorderStroke(1.dp, EmeraldVerified.copy(alpha = 0.5f))
                            ) {
                                Row(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .padding(12.dp),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                                ) {
                                    Icon(Icons.Default.CheckCircle, contentDescription = null, tint = EmeraldVerified)
                                    Text(
                                        text = msg,
                                        color = EmeraldVerified,
                                        fontSize = 12.sp,
                                        fontWeight = FontWeight.Bold
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Duplicate Conflict Alert (if previously triggered)
            if (duplicateErrorText != null) {
                Surface(
                    color = CrimsonContainer,
                    shape = RoundedCornerShape(12.dp),
                    border = androidx.compose.foundation.BorderStroke(1.dp, CrimsonAlert.copy(alpha = 0.5f))
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(14.dp),
                        verticalArrangement = Arrangement.spacedBy(10.dp)
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(10.dp)
                        ) {
                            Icon(Icons.Default.Warning, contentDescription = null, tint = CrimsonAlert)
                            Text(
                                text = duplicateErrorText!!,
                                color = CrimsonAlert,
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Medium,
                                lineHeight = 16.sp
                            )
                        }

                        if (conflictingStudent != null && pendingAggregatedVector != null) {
                            Button(
                                onClick = {
                                    val vec = pendingAggregatedVector!!
                                    val front = capturedFrontFaceBitmap ?: latestFrameBitmap
                                    if (front != null) {
                                        registerStudentWithVector(vec, front)
                                    }
                                },
                                modifier = Modifier.fillMaxWidth().height(44.dp),
                                colors = ButtonDefaults.buttonColors(containerColor = CrimsonAlert),
                                shape = RoundedCornerShape(8.dp)
                            ) {
                                Icon(Icons.Default.DeleteSweep, contentDescription = null, modifier = Modifier.size(16.dp))
                                Spacer(Modifier.width(6.dp))
                                Text(
                                    text = "DELETE '${conflictingStudent!!.name}' & ENROL NOW",
                                    fontSize = 11.sp,
                                    fontWeight = FontWeight.Bold
                                )
                            }
                        }
                    }
                }
            }

            // Successfully Enrolled Confirmation Card
            if (enrolledStudent != null) {
                Card(
                    colors = CardDefaults.cardColors(containerColor = LightSurface),
                    shape = RoundedCornerShape(14.dp),
                    border = androidx.compose.foundation.BorderStroke(1.dp, EmeraldVerified.copy(alpha = 0.5f)),
                    elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(16.dp),
                        verticalArrangement = Arrangement.spacedBy(12.dp)
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            Icon(Icons.Default.CheckCircle, contentDescription = null, tint = EmeraldVerified)
                            Text(
                                text = "STUDENT ENROLLED IN LOCAL DATABASE",
                                color = EmeraldVerified,
                                fontWeight = FontWeight.Bold,
                                fontSize = 13.sp
                            )
                        }

                        HorizontalDivider(color = LightCardBorder)

                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(14.dp)
                        ) {
                            StudentAvatar(
                                photoUri = enrolledStudent!!.photoUri,
                                size = 64.dp
                            )
                            Column(verticalArrangement = Arrangement.spacedBy(3.dp)) {
                                Text(
                                    text = enrolledStudent!!.name,
                                    color = TextPrimary,
                                    fontSize = 16.sp,
                                    fontWeight = FontWeight.Bold
                                )
                                Text(
                                    text = "ID: ${enrolledStudent!!.studentId}  •  Roll: ${enrolledStudent!!.rollNumber}",
                                    color = PrimaryBlue,
                                    fontSize = 12.sp,
                                    fontWeight = FontWeight.SemiBold
                                )
                                Text(
                                    text = "Course: ${enrolledStudent!!.course}  (${enrolledStudent!!.enrolledSessionIds.joinToString(", ")})",
                                    color = TextSecondary,
                                    fontSize = 11.sp
                                )
                            }
                        }

                        // Verified Multi-Angle Facial Captures (All 3 angles!)
                        Surface(
                            color = LightSubtle,
                            shape = RoundedCornerShape(12.dp),
                            border = androidx.compose.foundation.BorderStroke(1.dp, LightCardBorder)
                        ) {
                            Column(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(12.dp),
                                verticalArrangement = Arrangement.spacedBy(8.dp)
                            ) {
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Text(
                                        text = "CAPTURED MULTI-ANGLE FACIAL PROFILES",
                                        fontSize = 11.sp,
                                        fontWeight = FontWeight.Bold,
                                        color = PrimaryBlue,
                                        letterSpacing = 0.5.sp
                                    )
                                    Surface(
                                        color = EmeraldContainer,
                                        shape = RoundedCornerShape(6.dp)
                                    ) {
                                        Text(
                                            text = "3/3 CAPTURED",
                                            fontSize = 10.sp,
                                            fontWeight = FontWeight.Bold,
                                            color = EmeraldVerified,
                                            modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp)
                                        )
                                    }
                                }

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceEvenly
                                ) {
                                    AnglePhotoItem("1. Frontal (0°)", capturedFrontFaceBitmap)
                                    AnglePhotoItem("2. Left Angle (-18°)", capturedLeftFaceBitmap)
                                    AnglePhotoItem("3. Right Angle (+20°)", capturedRightFaceBitmap)
                                }
                            }
                        }

                        // 128-dim Embedding Vector Preview
                        Surface(
                            color = LightSubtle,
                            shape = RoundedCornerShape(8.dp),
                            border = androidx.compose.foundation.BorderStroke(1.dp, LightCardBorder)
                        ) {
                            Column(modifier = Modifier.padding(10.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                                Text(
                                    text = "Aggregated MobileFaceNet Biometric Vector Preview:",
                                    fontSize = 10.sp,
                                    color = TextSecondary,
                                    fontWeight = FontWeight.Bold
                                )
                                val emb = enrolledStudent!!.faceEmbedding
                                val snippet = emb.take(6).joinToString(", ") { String.format("%.3f", it) }
                                Text(
                                    text = "[$snippet, ... +${emb.size - 6} dimensions]",
                                    fontSize = 11.sp,
                                    color = PrimaryBlue,
                                    fontFamily = FontFamily.Monospace,
                                    fontWeight = FontWeight.SemiBold
                                )
                            }
                        }

                        Button(
                            onClick = onEnrollmentComplete,
                            modifier = Modifier.fillMaxWidth(),
                            colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue),
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Text("VIEW ALL STUDENTS IN DATABASE →", fontWeight = FontWeight.Bold)
                        }
                    }
                }
            }
        }
    }

    // IMMERSIVE AUTO-DETECT BIOMETRIC REGISTRATION MODAL POPUP
    if (showBiometricModal) {
        Dialog(
            onDismissRequest = { showBiometricModal = false },
            properties = DialogProperties(usePlatformDefaultWidth = false)
        ) {
            Surface(
                modifier = Modifier
                    .fillMaxWidth()
                    .fillMaxHeight(0.96f)
                    .padding(10.dp),
                shape = RoundedCornerShape(24.dp),
                color = LightSurface,
                shadowElevation = 10.dp
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .verticalScroll(rememberScrollState())
                        .padding(16.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    // Top Bar with Student Name and Close Button
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Column {
                            Text(
                                text = "Auto Biometric Enrollment",
                                fontSize = 18.sp,
                                fontWeight = FontWeight.Bold,
                                color = TextPrimary
                            )
                            Text(
                                text = "Student: ${if (name.isBlank()) "Candidate" else name} ($autoGeneratedStudentId)",
                                fontSize = 12.sp,
                                color = PrimaryBlue,
                                fontWeight = FontWeight.SemiBold
                            )
                        }
                        IconButton(onClick = { showBiometricModal = false }) {
                            Icon(Icons.Default.Close, contentDescription = "Close", tint = TextSecondary)
                        }
                    }

                    // Dynamic Guidance Banner
                    Surface(
                        color = when {
                            isSuccessAnimation -> EmeraldContainer
                            faceDetectedInCircle -> SkyContainer
                            else -> AmberContainer
                        },
                        shape = RoundedCornerShape(16.dp),
                        border = androidx.compose.foundation.BorderStroke(
                            1.dp,
                            when {
                                isSuccessAnimation -> EmeraldVerified.copy(alpha = 0.5f)
                                faceDetectedInCircle -> PrimaryBlue.copy(alpha = 0.4f)
                                else -> AmberOffline.copy(alpha = 0.4f)
                            }
                        )
                    ) {
                        Text(
                            text = guidanceMessage,
                            color = when {
                                isSuccessAnimation -> EmeraldVerified
                                faceDetectedInCircle -> PrimaryBlue
                                else -> AmberOffline
                            },
                            fontSize = 14.sp,
                            fontWeight = FontWeight.Bold,
                            textAlign = TextAlign.Center,
                            modifier = Modifier.padding(horizontal = 16.dp, vertical = 10.dp)
                        )
                    }

                    // CIRCULAR CAMERA PREVIEW (230dp DIAMETER) WITH AUTO-HOLD ANIMATION
                    Box(
                        modifier = Modifier
                            .size(230.dp)
                            .padding(4.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        // Outer Overall Progress Ring (0% -> 33% -> 66% -> 100%)
                        Canvas(modifier = Modifier.fillMaxSize()) {
                            val strokeWidth = 8.dp.toPx()
                            val diameter = size.minDimension - strokeWidth
                            val topLeft = Offset((size.width - diameter) / 2, (size.height - diameter) / 2)

                            // Track
                            drawArc(
                                color = Color(0xFFE2E8F0),
                                startAngle = -90f,
                                sweepAngle = 360f,
                                useCenter = false,
                                topLeft = topLeft,
                                size = Size(diameter, diameter),
                                style = Stroke(width = strokeWidth, cap = StrokeCap.Round)
                            )

                            // Step Progress
                            if (animatedProgress > 0f) {
                                drawArc(
                                    color = if (animatedProgress >= 1f) EmeraldVerified else PrimaryBlue,
                                    startAngle = -90f,
                                    sweepAngle = 360f * animatedProgress,
                                    useCenter = false,
                                    topLeft = topLeft,
                                    size = Size(diameter, diameter),
                                    style = Stroke(width = strokeWidth, cap = StrokeCap.Round)
                                )
                            }

                            // Dynamic Hold-Steady Progress Ring (Inner thin ring)
                            if (holdProgress > 0f && !isSuccessAnimation) {
                                val holdStroke = 3.5.dp.toPx()
                                val holdDiameter = diameter - strokeWidth - 5.dp.toPx()
                                val holdTopLeft = Offset((size.width - holdDiameter) / 2, (size.height - holdDiameter) / 2)
                                drawArc(
                                    color = EmeraldVerified,
                                    startAngle = -90f,
                                    sweepAngle = 360f * holdProgress,
                                    useCenter = false,
                                    topLeft = holdTopLeft,
                                    size = Size(holdDiameter, holdDiameter),
                                    style = Stroke(width = holdStroke, cap = StrokeCap.Round)
                                )
                            }
                        }

                        // Circular CameraX Aperture
                        Box(
                            modifier = Modifier
                                .size(188.dp)
                                .clip(CircleShape)
                                .background(Color(0xFF0F172A)),
                            contentAlignment = Alignment.Center
                        ) {
                            var isAnalyzingFrame by remember { mutableStateOf(false) }

                            AndroidView(
                                factory = { ctx ->
                                    val previewView = PreviewView(ctx)
                                    val cameraProviderFuture = ProcessCameraProvider.getInstance(ctx)

                                    cameraProviderFuture.addListener({
                                        try {
                                            val cameraProvider = cameraProviderFuture.get()
                                            val preview = Preview.Builder().build()
                                            val cameraSelector = CameraSelector.DEFAULT_FRONT_CAMERA

                                            preview.setSurfaceProvider(previewView.surfaceProvider)

                                            val imageAnalysis = ImageAnalysis.Builder()
                                                .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                                                .build()

                                            val analysisExecutor = Executors.newSingleThreadExecutor()

                                            imageAnalysis.setAnalyzer(analysisExecutor) { imageProxy ->
                                                try {
                                                    val rotation = imageProxy.imageInfo.rotationDegrees
                                                    val rawBitmap = imageProxy.toBitmap()
                                                    imageProxy.close()

                                                    // Rotate to upright & mirror horizontally for front camera
                                                    val matrix = Matrix()
                                                    if (rotation != 0) {
                                                        matrix.postRotate(rotation.toFloat())
                                                    }
                                                    matrix.postScale(-1f, 1f, rawBitmap.width / 2f, rawBitmap.height / 2f)
                                                    val upright = Bitmap.createBitmap(rawBitmap, 0, 0, rawBitmap.width, rawBitmap.height, matrix, true)

                                                    latestFrameBitmap = upright

                                                    // Skip frame if busy or already finished
                                                    if (isAnalyzingFrame || isProcessingAngle || isSuccessAnimation || !showBiometricModal) {
                                                        return@setAnalyzer
                                                    }

                                                    isAnalyzingFrame = true

                                                    scope.launch(Dispatchers.Default) {
                                                        try {
                                                            val faces = app.faceDetectorEngine.detectFaces(upright, 0)
                                                            withContext(Dispatchers.Main) {
                                                                if (faces.isEmpty()) {
                                                                    faceDetectedInCircle = false
                                                                    currentYaw = 0f
                                                                    currentPitch = 0f
                                                                    holdCount = 0
                                                                    holdProgress = 0f
                                                                    guidanceMessage = "Position your face inside the circle"
                                                                    return@withContext
                                                                }

                                                                val face = faces[0]
                                                                val box = face.boundingBox
                                                                val W = upright.width.toFloat()
                                                                val H = upright.height.toFloat()

                                                                // 1. STRICT FRAMING & CIRCLE CENTERING VALIDATION
                                                                val faceCenterX = box.centerX().toFloat()
                                                                val faceCenterY = box.centerY().toFloat()
                                                                val dx = abs(faceCenterX - W / 2f) / W
                                                                val dy = abs(faceCenterY - H / 2f) / H
                                                                val widthRatio = box.width().toFloat() / W
                                                                val heightRatio = box.height().toFloat() / H

                                                                val isCentered = dx <= 0.16f && dy <= 0.20f
                                                                val isProperScale = widthRatio in 0.20f..0.78f && heightRatio in 0.20f..0.82f
                                                                val isProperlyFramed = isCentered && isProperScale

                                                                if (!isProperlyFramed) {
                                                                    faceDetectedInCircle = false
                                                                    holdCount = 0
                                                                    holdProgress = 0f
                                                                    guidanceMessage = when {
                                                                        widthRatio < 0.20f -> "Move closer to camera"
                                                                        widthRatio > 0.78f -> "Move back slightly"
                                                                        else -> "Center your face inside the circle"
                                                                    }
                                                                    return@withContext
                                                                }

                                                                faceDetectedInCircle = true

                                                                // 2. Head Yaw Direction Inversion Fix:
                                                                // In front-camera mirrored bitmap 'upright':
                                                                // When user turns head LEFT, face.headEulerAngleY is positive (>0).
                                                                // When user turns head RIGHT, face.headEulerAngleY is negative (<0).
                                                                // We normalize to userYaw where:
                                                                // Negative (< -12°) = User turned LEFT
                                                                // Positive (> +12°) = User turned RIGHT
                                                                val userYaw = -face.headEulerAngleY
                                                                currentYaw = userYaw
                                                                currentPitch = face.headEulerAngleX

                                                                // Automatic progression based on current step
                                                                when (registrationStep) {
                                                                    1 -> {
                                                                        // Frontal Target: abs(userYaw) <= 12°, abs(pitch) <= 18°
                                                                        if (abs(userYaw) <= 12f && abs(currentPitch) <= 18f) {
                                                                            guidanceMessage = "Hold steady... Capturing Frontal"
                                                                            holdCount++
                                                                            holdProgress = (holdCount / 3f).coerceIn(0f, 1f)
                                                                            if (holdCount >= 3) {
                                                                                holdCount = 0
                                                                                holdProgress = 0f
                                                                                captureCurrentAngle(1, upright, face)
                                                                            }
                                                                        } else {
                                                                            holdCount = 0
                                                                            holdProgress = 0f
                                                                            guidanceMessage = "Look straight at the camera"
                                                                        }
                                                                    }
                                                                    2 -> {
                                                                        // Turn Head Left: User must turn head LEFT (userYaw <= -13f)
                                                                        if (userYaw <= -13f) {
                                                                            guidanceMessage = "Hold steady... Capturing Left Angle"
                                                                            holdCount++
                                                                            holdProgress = (holdCount / 3f).coerceIn(0f, 1f)
                                                                            if (holdCount >= 3) {
                                                                                holdCount = 0
                                                                                holdProgress = 0f
                                                                                captureCurrentAngle(2, upright, face)
                                                                            }
                                                                        } else if (userYaw >= 10f) {
                                                                            // User turned the WRONG way (turned right)!
                                                                            holdCount = 0
                                                                            holdProgress = 0f
                                                                            guidanceMessage = "You turned RIGHT! Please turn LEFT 👈"
                                                                        } else {
                                                                            holdCount = 0
                                                                            holdProgress = 0f
                                                                            guidanceMessage = "Now slowly turn your head LEFT 👈"
                                                                        }
                                                                    }
                                                                    3 -> {
                                                                        // Turn Head Right: User must turn head RIGHT (userYaw >= 13f)
                                                                        if (userYaw >= 13f) {
                                                                            guidanceMessage = "Hold steady... Capturing Right Angle"
                                                                            holdCount++
                                                                            holdProgress = (holdCount / 3f).coerceIn(0f, 1f)
                                                                            if (holdCount >= 3) {
                                                                                holdCount = 0
                                                                                holdProgress = 0f
                                                                                captureCurrentAngle(3, upright, face)
                                                                            }
                                                                        } else if (userYaw <= -10f) {
                                                                            // User turned the WRONG way (turned left)!
                                                                            holdCount = 0
                                                                            holdProgress = 0f
                                                                            guidanceMessage = "You turned LEFT! Please turn RIGHT 👉"
                                                                        } else {
                                                                            holdCount = 0
                                                                            holdProgress = 0f
                                                                            guidanceMessage = "Now slowly turn your head RIGHT 👉"
                                                                        }
                                                                    }
                                                                    4 -> {
                                                                        // Step 4: Liveness Challenge - Blink Both Eyes
                                                                        val leftEye = face.leftEyeOpenProbability ?: 1.0f
                                                                        val rightEye = face.rightEyeOpenProbability ?: 1.0f
                                                                        val isBlinking = leftEye < 0.28f && rightEye < 0.28f
                                                                        val isEyesOpen = leftEye > 0.65f && rightEye > 0.65f

                                                                        if (isBlinking) {
                                                                            blinkDetected = true
                                                                            guidanceMessage = "Blink detected! Open your eyes... ✓"
                                                                        } else if (blinkDetected && isEyesOpen) {
                                                                            // Full blink cycle completed!
                                                                            guidanceMessage = "3D Liveness Verified! Saving biometrics..."
                                                                            registrationStep = 5
                                                                            finalizeRegistration(capturedFrontFaceBitmap ?: upright)
                                                                        } else if (!blinkDetected) {
                                                                            guidanceMessage = "Step 4/4: Blink both eyes naturally 👁️"
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        } finally {
                                                            isAnalyzingFrame = false
                                                        }
                                                    }
                                                } catch (e: Exception) {
                                                    imageProxy.close()
                                                    isAnalyzingFrame = false
                                                }
                                            }

                                            cameraProvider.unbindAll()
                                            cameraProvider.bindToLifecycle(
                                                lifecycleOwner,
                                                cameraSelector,
                                                preview,
                                                imageAnalysis
                                            )
                                        } catch (e: Exception) {
                                            Log.e("ModalEnrollmentCamera", "Error binding camera", e)
                                        }
                                    }, ContextCompat.getMainExecutor(ctx))

                                    previewView
                                },
                                modifier = Modifier.fillMaxSize()
                            )

                            // Success Overlay with All 3 Captured Angles
                            if (isSuccessAnimation) {
                                Box(
                                    modifier = Modifier
                                        .fillMaxSize()
                                        .background(EmeraldVerified.copy(alpha = 0.92f)),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Column(
                                        horizontalAlignment = Alignment.CenterHorizontally,
                                        verticalArrangement = Arrangement.spacedBy(8.dp),
                                        modifier = Modifier.padding(12.dp)
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.CheckCircle,
                                            contentDescription = "Success",
                                            tint = Color.White,
                                            modifier = Modifier.size(44.dp)
                                        )
                                        Text(
                                            text = "4 BIOMETRIC CHECKS VERIFIED!",
                                            color = Color.White,
                                            fontWeight = FontWeight.Bold,
                                            fontSize = 12.sp,
                                            letterSpacing = 0.5.sp
                                        )
                                        Row(
                                            horizontalArrangement = Arrangement.spacedBy(6.dp),
                                            verticalAlignment = Alignment.CenterVertically
                                        ) {
                                            capturedFrontFaceBitmap?.let { bmp ->
                                                Image(
                                                    bitmap = bmp.asImageBitmap(),
                                                    contentDescription = "Front",
                                                    modifier = Modifier
                                                        .size(46.dp)
                                                        .clip(CircleShape)
                                                        .border(2.dp, Color.White, CircleShape),
                                                    contentScale = ContentScale.Crop
                                                )
                                            }
                                            capturedLeftFaceBitmap?.let { bmp ->
                                                Image(
                                                    bitmap = bmp.asImageBitmap(),
                                                    contentDescription = "Left",
                                                    modifier = Modifier
                                                        .size(46.dp)
                                                        .clip(CircleShape)
                                                        .border(2.dp, Color.White, CircleShape),
                                                    contentScale = ContentScale.Crop
                                                )
                                            }
                                            capturedRightFaceBitmap?.let { bmp ->
                                                Image(
                                                    bitmap = bmp.asImageBitmap(),
                                                    contentDescription = "Right",
                                                    modifier = Modifier
                                                        .size(46.dp)
                                                        .clip(CircleShape)
                                                        .border(2.dp, Color.White, CircleShape),
                                                    contentScale = ContentScale.Crop
                                                )
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                    // Live Head Angle Pill Feedback
                    Surface(
                        color = LightSubtle,
                        shape = RoundedCornerShape(8.dp),
                        border = androidx.compose.foundation.BorderStroke(1.dp, LightCardBorder)
                    ) {
                        Row(
                            modifier = Modifier.padding(horizontal = 12.dp, vertical = 6.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(6.dp)
                        ) {
                            Icon(
                                imageVector = if (faceDetectedInCircle) Icons.Default.Face else Icons.Default.FaceRetouchingOff,
                                contentDescription = null,
                                tint = if (faceDetectedInCircle) PrimaryBlue else TextMuted,
                                modifier = Modifier.size(16.dp)
                            )
                            val poseText = when {
                                !faceDetectedInCircle -> "Looking for face..."
                                abs(currentYaw) <= 10f -> "Frontal (0°)"
                                currentYaw < -10f -> "Left (${currentYaw.toInt()}°)"
                                else -> "Right (+${currentYaw.toInt()}°)"
                            }
                            Text(
                                text = "Head Pose: $poseText",
                                fontSize = 11.sp,
                                fontWeight = FontWeight.SemiBold,
                                color = if (faceDetectedInCircle) TextPrimary else TextMuted
                            )
                        }
                    }

                    // 4 Step Badges (Front, Left, Right, Blink)
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceEvenly
                    ) {
                        AngleBadge("1. Front", registrationStep > 1)
                        AngleBadge("2. Left", registrationStep > 2)
                        AngleBadge("3. Right", registrationStep > 3)
                        AngleBadge("4. Blink", registrationStep > 4)
                    }

                    // Duplicate Conflict Error in Modal
                    if (duplicateErrorText != null) {
                        Surface(
                            color = CrimsonContainer,
                            shape = RoundedCornerShape(12.dp),
                            border = androidx.compose.foundation.BorderStroke(1.dp, CrimsonAlert.copy(alpha = 0.5f))
                        ) {
                            Column(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(12.dp),
                                verticalArrangement = Arrangement.spacedBy(8.dp)
                            ) {
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                                ) {
                                    Icon(Icons.Default.Warning, contentDescription = null, tint = CrimsonAlert)
                                    Text(
                                        text = duplicateErrorText!!,
                                        color = CrimsonAlert,
                                        fontSize = 11.sp,
                                        fontWeight = FontWeight.Medium,
                                        lineHeight = 15.sp
                                    )
                                }

                                if (conflictingStudent != null && pendingAggregatedVector != null) {
                                    Button(
                                        onClick = {
                                            val vec = pendingAggregatedVector!!
                                            val front = capturedFrontFaceBitmap ?: latestFrameBitmap
                                            if (front != null) {
                                                registerStudentWithVector(vec, front)
                                            }
                                        },
                                        modifier = Modifier.fillMaxWidth().height(42.dp),
                                        colors = ButtonDefaults.buttonColors(containerColor = CrimsonAlert),
                                        shape = RoundedCornerShape(8.dp)
                                    ) {
                                        Icon(Icons.Default.DeleteSweep, contentDescription = null, modifier = Modifier.size(16.dp))
                                        Spacer(Modifier.width(6.dp))
                                        Text(
                                            text = "DELETE '${conflictingStudent!!.name}' & RE-ENROL NOW",
                                            fontSize = 11.sp,
                                            fontWeight = FontWeight.Bold
                                        )
                                    }
                                }
                            }
                        }
                    }

                    // Action Controls: Restart & Manual Fallback Button
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(10.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        OutlinedButton(
                            onClick = {
                                capturedVectors.clear()
                                capturedFrontFaceBitmap = null
                                capturedLeftFaceBitmap = null
                                capturedRightFaceBitmap = null
                                registrationStep = 1
                                blinkDetected = false
                                holdCount = 0
                                holdProgress = 0f
                                firstTurnDirection = 0
                                isProcessingAngle = false
                                isSuccessAnimation = false
                                duplicateErrorText = null
                                conflictingStudent = null
                                pendingAggregatedVector = null
                                guidanceMessage = "Look straight at the camera"
                            },
                            shape = RoundedCornerShape(10.dp),
                            modifier = Modifier.weight(1f)
                        ) {
                            Icon(Icons.Default.RestartAlt, contentDescription = null, modifier = Modifier.size(16.dp))
                            Spacer(Modifier.width(4.dp))
                            Text("Reset", fontSize = 13.sp)
                        }

                        // Manual Capture Override Button
                        Button(
                            onClick = {
                                val frame = latestFrameBitmap
                                if (frame != null) {
                                    scope.launch {
                                        val faces = app.faceDetectorEngine.detectFaces(frame, 0)
                                        if (faces.isNotEmpty()) {
                                            if (registrationStep <= 3) {
                                                captureCurrentAngle(registrationStep, frame, faces[0])
                                            } else if (registrationStep == 4) {
                                                registrationStep = 5
                                                finalizeRegistration(capturedFrontFaceBitmap ?: frame)
                                            }
                                        }
                                    }
                                }
                            },
                            shape = RoundedCornerShape(10.dp),
                            modifier = Modifier.weight(2f),
                            colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue),
                            enabled = !isProcessingAngle && registrationStep <= 4
                        ) {
                            if (isProcessingAngle) {
                                CircularProgressIndicator(modifier = Modifier.size(18.dp), color = Color.White)
                                Spacer(Modifier.width(6.dp))
                                Text("Processing...", fontSize = 13.sp)
                            } else {
                                Icon(Icons.Default.CameraAlt, contentDescription = null, modifier = Modifier.size(16.dp))
                                Spacer(Modifier.width(6.dp))
                                Text(
                                    if (registrationStep == 4) "Verify Blink & Register" else "Manual Capture (${registrationStep}/4)",
                                    fontSize = 12.sp,
                                    fontWeight = FontWeight.Bold
                                )
                            }
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun AngleBadge(label: String, isDone: Boolean) {
    Surface(
        color = if (isDone) EmeraldContainer else LightSubtle,
        shape = RoundedCornerShape(8.dp),
        border = androidx.compose.foundation.BorderStroke(
            1.dp,
            if (isDone) EmeraldVerified.copy(alpha = 0.5f) else LightCardBorder
        )
    ) {
        Row(
            modifier = Modifier.padding(horizontal = 10.dp, vertical = 6.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(4.dp)
        ) {
            Icon(
                imageVector = if (isDone) Icons.Default.CheckCircle else Icons.Default.RadioButtonUnchecked,
                contentDescription = null,
                tint = if (isDone) EmeraldVerified else TextMuted,
                modifier = Modifier.size(14.dp)
            )
            Text(
                text = label,
                fontSize = 11.sp,
                fontWeight = if (isDone) FontWeight.Bold else FontWeight.Normal,
                color = if (isDone) EmeraldVerified else TextSecondary
            )
        }
    }
}

@Composable
private fun AnglePhotoItem(label: String, bitmap: Bitmap?) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(4.dp)
    ) {
        Surface(
            shape = RoundedCornerShape(10.dp),
            border = androidx.compose.foundation.BorderStroke(1.dp, PrimaryBlue.copy(alpha = 0.35f)),
            color = LightSurface,
            modifier = Modifier.size(72.dp)
        ) {
            if (bitmap != null) {
                Image(
                    bitmap = bitmap.asImageBitmap(),
                    contentDescription = label,
                    modifier = Modifier.fillMaxSize(),
                    contentScale = ContentScale.Crop
                )
            } else {
                Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                    Icon(Icons.Default.Face, contentDescription = null, tint = TextMuted)
                }
            }
        }
        Text(
            text = label,
            fontSize = 10.sp,
            fontWeight = FontWeight.SemiBold,
            color = TextSecondary
        )
    }
}
